FROM ubuntu:24.04

LABEL org.opencontainers.image.source=https://github.com/smartscope-org/smartscopeai
LABEL org.opencontainers.image.title=SmartScopeAI
LABEL org.opencontainers.image.description="SmartScope AI algorithms wrapped with a celery interface."
LABEL org.opencontainers.image.licenses=BSD-3-Clause

RUN apt-get update && apt-get install -y \
        build-essential ffmpeg libsm6 libxext6 wget python3-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Download the latest installer, install it and then remove it
ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh

# Set up the UV environment path correctly
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /app

COPY ./pyproject.toml .

ENV UV_LINK_MODE=copy


COPY pyproject.toml uv.lock* ./

# If you haven't updated pyproject.toml yet, this will still fail on llvmlite
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --extra cpu

COPY ./template_files /opt/template_files
# The following secrets are available during build time
RUN useradd --create-home appuser
RUN mkdir -p /opt/logs && chown appuser /opt/logs 
# Ensure the log directory is writable by the appuser
USER appuser


COPY ./SmartscopeAI SmartscopeAI 


# Set up environment variables for production
ENV PATH="/app/.venv/bin:$PATH"
ENV TEMPLATE_FILES="/opt/template_files/"
ENV NUMBA_CACHE_DIR="/tmp/numba_cache"
ENV LOGDIR="/opt/logs/" 
# Set the log directory to a writable location

# Start the application with Uvicorn in production mode, using environment variable references
CMD ["celery", "-A", "SmartscopeAI.interfaces.celery.app", "worker", "--loglevel=DEBUG", "--pool=solo"]